#!/usr/bin/env bash

# Enter a word ⮐
# View definitions & select from a list of spelling corrections  ⮐
# Copy it to the clipboard ⚡️
#
# For Linux and macOS.
#
# Dependencies:
# - datamuse API
# - fzf
# - jq
# - curl

word=$(echo "" | fzf \
	--padding=1 \
	--print-query \
	--prompt="spell " \
	--reverse)

[[ -z "$word" ]] && exit 0

suggestion=$(
	curl -s "https://api.datamuse.com/words?sp=$word" |
		jq -e -r '.[].word' |
		fzf \
			--padding=1 \
			--preview-window=up,wrap \
			--reverse \
			--preview="
				curl -s 'https://api.dictionaryapi.dev/api/v2/entries/en/{}' |
				jq -e -r '.[0].meanings[0].definitions[0].definition' 2>/dev/null || \
				echo 'No definition found.'
			"
)

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
	echo -n $suggestion | xclip -selection clipboard
elif [[ "$OSTYPE" == "darwin"* ]]; then
	echo -n $suggestion | pbcopy
else
	echo "Unsupported operating system: $OSTYPE"
	exit 1
fi
