#!/usr/bin/env bash

# CLI to launch macOS' Dictionary app with a provided search word.

word=$(echo "" | fzf \
	--padding=1 \
	--print-query \
	--prompt="define " \
	--reverse)

[[ -z "$word" ]] && exit 0

open "dict://$word"
