#!/usr/bin/env bash

# Add words to a list of words-to-be-ingnored by a spell checker.
#
# Usage:
# - Run words.
# - Input space delimited words.
# - Press enter to add the words to WORD_FILE.

WORD_FILE=$HOME/.words.txt

words=($(echo "" | fzf \
	--padding=1 \
	--print-query \
	--prompt="words " \
	--reverse))

[[ -z "${words// /}" ]] && exit 0

for word in "${words[@]}"; do
	echo "$word" | awk '{print tolower($0)}' >>$WORD_FILE
done

sort -o $WORD_FILE $WORD_FILE
